### ISSUE TITLE
How to run the build for production ?

### ISSUE THREAD

**Issue by vilain-corentin** [phaserjs/template-svelte#3]
Hello, thank you very much for this template which has enabled me to learn a lot!

I'm still a noob on these technos and out of curiosity, I wanted to see what the build for production looks like.

So I ran `npm run build`, which created a “build” folder that looks good, but I can't see how to render this build.

I tested `node build` but I get the following error:
```
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '/home/platon/Project/mokaonline-front/build'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/modules/run_main:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I also tested `serve -l 8080 -s build` and got 
```
Uncaught (in promise) SyntaxError: Unexpected token ‘<’, ‘<!doctype html>’ is not valid JSON
    at JSON.parse (<anonymous>)
    at entry.D1j-sW8n.js:1:26488
```

What is the right way to do it? 

Thanks in advance and have a nice day.

**Comment by kolown2007** [comment]
> Hello, thank you very much for this template which has enabled me to learn a lot!
> 
> I'm still a noob on these technos and out of curiosity, I wanted to see what the build for production looks like.
> 
> So I ran `npm run build`, which created a “build” folder that looks good, but I can't see how to render this build.
> 
> I tested `node build` but I get the following error:
> 
> ```
> node:internal/modules/cjs/loader:1146
>   throw err;
>   ^
> 
> Error: Cannot find module '/home/platon/Project/mokaonline-front/build'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
>     at Module._load (node:internal/modules/cjs/loader:984:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
>     at node:internal/modules/run_main:28:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```
> 
> I also tested `serve -l 8080 -s build` and got
> 
> ```
> Uncaught (in promise) SyntaxError: Unexpected token ‘<’, ‘<!doctype html>’ is not valid JSON
>     at JSON.parse (<anonymous>)
>     at entry.D1j-sW8n.js:1:26488
> ```
> 
> What is the right way to do it?
> 
> Thanks in advance and have a nice day.
> 
> Translated with DeepL.com (free version)

hello,
good day

for quick preview you can cd to the build folder and then run live-server

**Comment by vilain-corentin** [comment]
~~Thank you for this quick response, indeed it works with live-server but the doc says "Use it for hacking your HTML/JavaScript/CSS files, but not for deploying the final site."~~

~~For a real production start-up, how should I go about it? (in a very basic way, just to start the server)~~

It's okay, I got what I wanted.

In fact, since I've added server-side processing, the template adapter isn't adapted.

You need to use `@sveltejs/adapter-node` then launch the server with node and everything works fine!

Have a nice evening
